import 'package:equatable/equatable.dart';

/// Represents the core data for a Service Provider in the domain layer.
class ServiceProviderEntity extends Equatable {
  final String? id; // Optional, will be generated by Firebase
  final String nameOfService;
  final String nameOfEmployee;
  final String address;

  const ServiceProviderEntity({
    this.id,
    required this.nameOfService,
    required this.nameOfEmployee,
    required this.address,
  });

  @override
  List<Object?> get props => [id, nameOfService, nameOfEmployee, address];
}